/*=========================================================
 RANSAN TRAVELS
 FARE CALCULATOR MODERN ENHANCEMENT

 IMPORTANT:
 ----------------------------------------------------------
 - Does NOT replace rsCalculateFare2026()
 - Does NOT replace rsLoadFareVehicles2026()
 - Does NOT replace rsToggleFareMode()
 - Does NOT calculate prices independently
=========================================================*/

(function () {

    "use strict";


    document.addEventListener(
        "DOMContentLoaded",
        function () {


            const section =
                document.querySelector(
                    ".rs-fare-modern-2026"
                );


            if (!section) {

                return;

            }


            const vehicle =
                section.querySelector(
                    "#rsFareVehicle"
                );


            const kmInput =
                section.querySelector(
                    "#rsFareKm"
                );


            const daysInput =
                section.querySelector(
                    "#rsFareDays"
                );


            const result =
                section.querySelector(
                    "#rsFareResult"
                );


            const resultBadge =
                section.querySelector(
                    ".rs-result-badge"
                );


            const statusTitle =
                section.querySelector(
                    "#rsFareEstimateStatusTitle"
                );


            const statusText =
                section.querySelector(
                    "#rsFareEstimateStatusText"
                );


            const enquireButton =
                section.querySelector(
                    "#rsFareEnquireBtn"
                );


            if (
                !vehicle ||
                !result ||
                !enquireButton
            ) {

                return;

            }


            /*
             * Stores only information already calculated
             * by the existing calculator.
             */

            let currentEstimate =
                null;


            /*=================================================
            DEFAULT STATE
            =================================================*/

            function setWaitingState() {


                currentEstimate =
                    null;


                enquireButton.disabled =
                    true;


                if (resultBadge) {


                    resultBadge.classList.remove(
                        "rs-fare-result-ready"
                    );


                    resultBadge.innerHTML =
                        `
                        <span></span>
                        Ready to Calculate
                        `;

                }


                if (statusTitle) {

                    statusTitle.textContent =
                        "Select your trip details";

                }


                if (statusText) {

                    statusText.textContent =
                        "Your calculated estimate will appear above.";

                }

            }


            /*=================================================
            READ SUCCESSFUL RESULT

            We read the DOM generated by the EXISTING
            rsCalculateFare2026() function.
            =================================================*/

            function readCalculatedEstimate() {


                const priceElement =
                    result.querySelector(
                        ".rs-fare-price"
                    );


                /*
                 * Existing validation errors render
                 * .rs-fare-error instead.
                 */

                const errorElement =
                    result.querySelector(
                        ".rs-fare-error"
                    );


                if (
                    errorElement ||
                    !priceElement
                ) {


                    setWaitingState();

                    return;

                }


                const price =
                    priceElement.textContent
                        .trim();


                /*
                 * Ignore initial ₹0 placeholder.
                 */

                if (
                    !price ||
                    price === "₹0"
                ) {


                    setWaitingState();

                    return;

                }


                const selectedOption =
                    vehicle.options[
                        vehicle.selectedIndex
                    ];


                const vehicleName =
                    selectedOption
                        ? (
                            selectedOption.dataset.vehicle ||
                            selectedOption.textContent.trim()
                        )
                        : "";


                const rate =
                    vehicle.value || "";


                const isPerDay =
                    rate
                        .toLowerCase()
                        .includes(
                            "/day"
                        );


                let usage =
                    "";


                if (
                    isPerDay &&
                    daysInput
                ) {

                    usage =
                        `${daysInput.value || 1} Day(s)`;

                } else if (kmInput) {

                    usage =
                        `${kmInput.value || 0} KM`;

                }


                currentEstimate = {

                    price:
                        price,

                    vehicle:
                        vehicleName,

                    rate:
                        rate,

                    fareType:
                        isPerDay
                            ? "Per Day"
                            : "Per KM",

                    usage:
                        usage

                };


                enquireButton.disabled =
                    false;


                if (resultBadge) {


                    resultBadge.classList.add(
                        "rs-fare-result-ready"
                    );


                    resultBadge.innerHTML =
                        `
                        <span></span>
                        Estimate Ready
                        `;

                }


                if (statusTitle) {

                    statusTitle.textContent =
                        "Estimate ready for enquiry";

                }


                if (statusText) {

                    statusText.textContent =
                        `${vehicleName} • ${usage}`;

                }

            }


            /*=================================================
            OBSERVE EXISTING CALCULATOR OUTPUT

            rsCalculateFare2026() replaces innerHTML.
            MutationObserver reacts after that happens.
            =================================================*/

            const resultObserver =
                new MutationObserver(
                    function () {

                        window.setTimeout(
                            readCalculatedEstimate,
                            0
                        );

                    }
                );


            resultObserver.observe(
                result,
                {
                    childList:
                        true,

                    subtree:
                        true,

                    characterData:
                        true
                }
            );


            /*=================================================
            INPUT CHANGE

            We only reset the ENQUIRY STATUS.
            Existing fare mode logic remains untouched.
            =================================================*/

            vehicle.addEventListener(
                "change",
                function () {

                    setWaitingState();

                }
            );


            if (kmInput) {


                kmInput.addEventListener(
                    "input",
                    function () {

                        setWaitingState();

                    }
                );

            }


            if (daysInput) {


                daysInput.addEventListener(
                    "input",
                    function () {

                        setWaitingState();

                    }
                );

            }


            /*=================================================
            ENQUIRE WITH ESTIMATE
            =================================================*/

            enquireButton.addEventListener(
                "click",
                function () {


                    if (!currentEstimate) {

                        return;

                    }


                    /*
                     * Open existing Premium Quote modal.
                     */

                    if (
                        typeof window.openPremiumQuote ===
                        "function"
                    ) {

                        window.openPremiumQuote();

                    }


                    /*
                     * Existing Premium Quote already contains
                     * a valid "Car Rental" option.
                     */

                    const service =
                        document.getElementById(
                            "pqService"
                        );


                    if (service) {

                        service.value =
                            "Car Rental";

                    }


                    /*
                     * Carry the estimate into the existing
                     * enquiry message.
                     */

                    const message =
                        document.getElementById(
                            "pqMessage"
                        );


                    if (message) {


                        const estimateText =
                            [
                                "Fare Calculator Estimate",
                                `Vehicle: ${currentEstimate.vehicle}`,
                                `Estimated Fare: ${currentEstimate.price}`,
                                `Rate: ${currentEstimate.rate}`,
                                `Fare Basis: ${currentEstimate.fareType}`,
                                `Usage: ${currentEstimate.usage}`,
                                "Note: Toll, parking, driver bata and other applicable trip charges may be extra."
                            ]
                                .join(
                                    "\n"
                                );


                        message.value =
                            estimateText;

                    }

                }
            );


            setWaitingState();

        }
    );

})();